### ISSUE TITLE
Why is this called "deep denoiser"

### ISSUE THREAD

**Issue by bsavery** [DeepBlender/DeepDenoiser#1]
Deep rendering is something very specific . https://www.fxguide.com/featured/the-art-of-deep-compositing/ Which as far as I can tell, this does not use.  And can't tell what exactly is "deep" about this method.  Although feel free to correct me.  I'd suggest picking a more clear name like "tensordenoiser" or "AIDenoiser" or "Machine Learning Denoiser".

**Comment by bsavery** [comment]
Edit:  I suppose you're using Deep learning, maybe call it "Deep Learning Denoiser" so it's not confused with deep compositing which also uses aovs/passes?

**Comment by DeepBlender** [comment]
Thanks for the feedback. I wasn't aware that the name could be misleading. Please consider it to be a temporary name. If this project was merged with Cycles or Blender, it would anyways loose its name. I am going to make it clear in the readme file to avoid confusions.

Edit:
I changed the project description and added the readme file. This should hopefully be enough for now to avoid confusions.

**Comment by DeepBlender** [comment]
I changed the project description and added the readme file. This should hopefully be enough for now to avoid confusions.

**Comment by bsavery** [comment]
No worries!  Just offering a suggestion to help out.
