### ISSUE TITLE
Viewport denoising support 

### ISSUE THREAD

**Issue by mistajuliax** [DeepBlender/DeepDenoiser#3]
It would be awesome to get denoising in blender viewport... Is it something doable ? Is the project is still in developement ?

**Comment by DeepBlender** [comment]
The project is still being developed. Right now, I am doing a lot behind the scenes, like rendering to create a larger dataset and experimenting with neural network architectures, as well as learning about the Blender code base.

Denoising in the viewport is on my TODO list! I am closing the report as it is not an issue, but a feature request.
